### ISSUE TITLE
AVCS Sends full database over and over

### ISSUE THREAD

**Issue by mrkmg** [Lu5ck/AnotherVehicleClaimSystem#4]
I was doing some packet inspection of our MP Server (WastelandRP) and found that occasionally, one client will be streamed the entire AVCS Database over and over. I have a dump of the packets for WireShark as proof.

I think this *could* be triggered in https://github.com/Lu5ck/AnotherVehicleClaimSystem/blob/main/contents/mods/AnotherVehicleClaimSystemB41/media/lua/client/AVCSClient.lua

My theory is:

1. The player has no `AVCS.dbByVehicleSQLID` or `AVCS.dbByPlayerID`. (Why, idk maybe bug or desync?)
2. A series of changes happens on the server (vehicles moved, permissions changed, w/e).
3. Those changes all hit the player at once via normal sendServerCommand
4. AVCS client starts to process them, and every single one of them triggers another `ModData.request`

Possible solution:

Add in a `lastModDataSync` which stores a timestamp. If that timestamp is lets say under 5 seconds, do not request again.

Some notes:

- We are a veryyy busy server with >80 people on for many hours a day
- We have A LOT of claimed cars. Maybe the desync has to do with packets being dropped or lost?

**Comment by Lu5ck** [comment]
I have looked into it. This happen because the users have yet to fully connect to the server thus PZ API is not fully initialized therefore some of the variables are also not initialized but at the same time certain PZ API already start running. Very good catch, didn't know PZ operate this way. Will push a fix out soon, once I tested the fix working properly.

**Comment by Lu5ck** [comment]
https://github.com/Lu5ck/AnotherVehicleClaimSystem/commit/a77c3abe2784629c612b4ac582ea7aa55c17719f
